// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface AccessData {
    client_id: string
    user_id: string
    token: string
    refresh_token: string
    redirect_uri: string
    expires_at: number
    scope: string
}

declare interface AccessResponse {
    access_token: string
    token_type: string
    expires_in: number
    scope: string
    refresh_token: string
}


