// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Audit {
    id: string
    create_at: number
    user_id: string
    action: string
    extra_info: string
    ip_address: string
    session_id: string
}


