// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface AuthData {
    client_id: string
    user_id: string
    code: string
    expires_in: number
    create_at: number
    redirect_uri: string
    state: string
    scope: string
}

declare interface AuthorizeRequest {
    response_type: string
    client_id: string
    redirect_uri: string
    scope: string
    state: string
}


