// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface ChannelView {
    channel_id: string
    prev_channel_id: string
}

declare interface ChannelViewResponse {
    status: string
}


