// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface ChannelStats {
    channel_id: string
    member_count: number
}


