// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface ChannelUnread {
    team_id: string
    channel_id: string
    msg_count: number
    mention_count: number
}

declare interface ChannelMember {
    channel_id: string
    user_id: string
    roles: string
    last_viewed_at: number
    msg_count: number
    mention_count: number
    notify_props: Map<string, string>
    last_update_at: number
    scheme_user: boolean
    scheme_admin: boolean
    explicit_roles: string
}


