// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Channel {
    id: string
    create_at: number
    update_at: number
    delete_at: number
    team_id: string
    type: string
    display_name: string
    name: string
    header: string
    purpose: string
    last_post_at: number
    total_msg_count: number
    extra_update_at: number
    creator_id: string
    scheme_id: string
}

declare interface ChannelWithTeamData {
    team_display_name: string
    team_name: string
    team_update_at: number
}

declare interface ChannelPatch {
    display_name: string
    name: string
    header: string
    purpose: string
}


