// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface ClusterStats {
    id: string
    total_websocket_connections: number
    total_read_db_connections: number
    total_master_db_connections: number
}


