// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface ClusterInfo {
    id: string
    version: string
    config_hash: string
    ipaddress: string
    hostname: string
}


