// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface CommandResponse {
    response_type: string
    text: string
    username: string
    channel_id: string
    icon_url: string
    type: string
    props: Map<string, any>
    goto_location: string
    trigger_id: string
}


