// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface CommandArgs {
    user_id: string
    channel_id: string
    team_id: string
    root_id: string
    parent_id: string
    trigger_id: string
    command: string
}


