// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Command {
    id: string
    token: string
    create_at: number
    update_at: number
    delete_at: number
    creator_id: string
    team_id: string
    trigger: string
    method: string
    username: string
    icon_url: string
    auto_complete: boolean
    auto_complete_desc: string
    auto_complete_hint: string
    display_name: string
    description: string
    url: string
}


