// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Compliance {
    id: string
    create_at: number
    user_id: string
    status: string
    count: number
    desc: string
    type: string
    start_at: number
    end_at: number
    keywords: string
    emails: string
}


