// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface ServiceSettings {
    EnableOnlyAdminIntegrations: boolean
    RestrictCustomEmojiCreation: string
    RestrictPostDelete: string
    AllowEditPost: string
}

declare interface TeamSettings {
    EnableTeamCreation: boolean
    RestrictTeamInvite: string
    RestrictPublicChannelManagement: string
    RestrictPrivateChannelManagement: string
    RestrictPublicChannelCreation: string
    RestrictPrivateChannelCreation: string
    RestrictPublicChannelDeletion: string
    RestrictPrivateChannelDeletion: string
    RestrictPrivateChannelManageMembers: string
}


