// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface DataRetentionPolicy {
    message_deletion_enabled: boolean
    file_deletion_enabled: boolean
    message_retention_cutoff: number
    file_retention_cutoff: number
}


