// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Emoji {
    id: string
    create_at: number
    update_at: number
    delete_at: number
    creator_id: string
    name: string
}


