// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface FileInfo {
    id: string
    user_id: string
    post_id: string
    create_at: number
    update_at: number
    delete_at: number
    name: string
    extension: string
    size: number
    mime_type: string
    width: number
    height: number
    has_preview_image: boolean
}


