// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface GroupMember {
    group_id: string
    user_id: string
    create_at: number
    delete_at: number
}


