// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface GroupSyncable {
    group_id: string
    can_leave: boolean
    auto_add: boolean
    create_at: number
    delete_at: number
    update_at: number
}

declare interface GroupSyncablePatch {
    can_leave: boolean
    auto_add: boolean
}


