// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface IncomingWebhook {
    id: string
    create_at: number
    update_at: number
    delete_at: number
    user_id: string
    channel_id: string
    team_id: string
    display_name: string
    description: string
    username: string
    icon_url: string
    channel_locked: boolean
}

declare interface IncomingWebhookRequest {
    text: string
    username: string
    icon_url: string
    channel: string
    props: Map<string, any>
    type: string
}


