// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface DoPostActionRequest {
    selected_option: string
}

declare interface PostAction {
    id: string
    name: string
    type: string
    data_source: string
}

declare interface PostActionOptions {
    text: string
    value: string
}

declare interface PostActionIntegration {
    url: string
}

declare interface PostActionIntegrationRequest {
    user_id: string
    channel_id: string
    team_id: string
    post_id: string
    trigger_id: string
    type: string
    data_source: string
}

declare interface PostActionIntegrationResponse {
    ephemeral_text: string
}

declare interface PostActionAPIResponse {
    status: string
    trigger_id: string
}

declare interface Dialog {
    callback_id: string
    title: string
    icon_url: string
    submit_label: string
    notify_on_cancel: boolean
    state: string
}

declare interface DialogElement {
    display_name: string
    name: string
    type: string
    subtype: string
    default: string
    placeholder: string
    help_text: string
    optional: boolean
    min_length: number
    max_length: number
    data_source: string
}

declare interface OpenDialogRequest {
    trigger_id: string
    url: string
}

declare interface SubmitDialogRequest {
    type: string
    url: string
    callback_id: string
    state: string
    user_id: string
    channel_id: string
    team_id: string
    cancelled: boolean
}


