// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Job {
    id: string
    type: string
    priority: number
    create_at: number
    start_at: number
    last_activity_at: number
    status: string
    progress: number
}


