// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface LicenseRecord {
    id: string
    create_at: number
}

declare interface License {
    id: string
    issued_at: number
    starts_at: number
    expires_at: number
    sku_name: string
    sku_short_name: string
}

declare interface Customer {
    id: string
    name: string
    email: string
    company: string
    phone_number: string
}

declare interface Features {
    users: number
    ldap: boolean
    ldap_groups: boolean
    mfa: boolean
    google_oauth: boolean
    office365_oauth: boolean
    compliance: boolean
    cluster: boolean
    metrics: boolean
    mhpns: boolean
    saml: boolean
    elastic_search: boolean
    announcement: boolean
    theme_management: boolean
    email_notification_contents: boolean
    data_retention: boolean
    message_export: boolean
    custom_permissions_schemes: boolean
    custom_terms_of_service: boolean
    future_features: boolean
}


