// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface PluginOption {
    display_name: string
    value: string
}

declare interface PluginSetting {
    key: string
    display_name: string
    type: string
    help_text: string
    regenerate_help_text: string
    placeholder: string
}

declare interface PluginSettingsSchema {
    header: string
    footer: string
}

declare interface Manifest {
    id: string
    name: string
    description: string
    version: string
    min_server_version: string
}

declare interface ManifestServer {
    executable: string
}

declare interface ManifestWebapp {
    bundle_path: string
}


