// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface OAuthApp {
    id: string
    creator_id: string
    create_at: number
    update_at: number
    client_secret: string
    name: string
    description: string
    icon_url: string
    callback_urls: Array<string>
    homepage: string
    is_trusted: boolean
}


