// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface OutgoingWebhook {
    id: string
    token: string
    create_at: number
    update_at: number
    delete_at: number
    creator_id: string
    channel_id: string
    team_id: string
    trigger_words: Array<string>
    trigger_when: number
    callback_urls: Array<string>
    display_name: string
    description: string
    content_type: string
    username: string
    icon_url: string
}

declare interface OutgoingWebhookPayload {
    token: string
    team_id: string
    team_domain: string
    channel_id: string
    channel_name: string
    timestamp: number
    user_id: string
    user_name: string
    post_id: string
    text: string
    trigger_word: string
    file_ids: string
}

declare interface OutgoingWebhookResponse {
    text: string
    username: string
    icon_url: string
    props: Map<string, any>
    type: string
    response_type: string
}


