// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Permission {
    id: string
    name: string
    description: string
    scope: string
}


