// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface PluginStatus {
    plugin_id: string
    cluster_id: string
    plugin_path: string
    state: number
    name: string
    description: string
    version: string
}


