// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface PluginKeyValue {
    plugin_id: string
    key: string
    expire_at: number
}


