// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Post {
    id: string
    create_at: number
    update_at: number
    edit_at: number
    delete_at: number
    is_pinned: boolean
    user_id: string
    channel_id: string
    root_id: string
    parent_id: string
    original_id: string
    message: string
    message_source: string
    type: string
    props: Map<string, any>
    hashtags: string
    filenames: Array<string>
    file_ids: Array<string>
    pending_post_id: string
    has_reactions: boolean
}

declare interface PostEphemeral {
    user_id: string
}

declare interface PostPatch {
    is_pinned: boolean
    message: string
    props: Map<string, any>
    file_ids: Array<string>
    has_reactions: boolean
}

declare interface SearchParameter {
    terms: string
    is_or_search: boolean
    time_zone_offset: number
    page: number
    per_page: number
    include_deleted_channels: boolean
}

declare interface PostForIndexing {
    team_id: string
    parent_create_at: number
}


