// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Preference {
    user_id: string
    category: string
    name: string
    value: string
}


