// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface PushNotification {
    platform: string
    server_id: string
    device_id: string
    category: string
    sound: string
    message: string
    badge: number
    cont_ava: number
    team_id: string
    channel_id: string
    post_id: string
    root_id: string
    channel_name: string
    type: string
    sender_id: string
    override_username: string
    override_icon_url: string
    from_webhook: string
    version: string
}


