// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Reaction {
    user_id: string
    post_id: string
    emoji_name: string
    create_at: number
}


