// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Role {
    id: string
    name: string
    display_name: string
    description: string
    create_at: number
    update_at: number
    delete_at: number
    scheme_managed: boolean
    built_in: boolean
}


