// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface SamlCertificateStatus {
    idp_certificate_file: boolean
    private_key_file: boolean
    public_certificate_file: boolean
}


