// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface SecurityBulletin {
    id: string
    applies_to_version: string
}


