// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Session {
    id: string
    token: string
    create_at: number
    expires_at: number
    last_activity_at: number
    user_id: string
    device_id: string
    roles: string
    is_oauth: boolean
    props: Map<string, string>
}


