// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface SlackAttachment {
    id: number
    fallback: string
    color: string
    pretext: string
    author_name: string
    author_link: string
    author_icon: string
    title: string
    title_link: string
    text: string
    image_url: string
    thumb_url: string
    footer: string
    footer_icon: string
}

declare interface SlackAttachmentField {
    title: string
    short: boolean
}


