// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Status {
    user_id: string
    status: string
    manual: boolean
    last_activity_at: number
    active_channel: string
}


