// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface SuggestCommand {
    suggestion: string
    description: string
}


