// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface SwitchRequest {
    current_service: string
    new_service: string
    email: string
    password: string
    new_password: string
    mfa_code: string
    ldap_id: string
}


