// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface System {
    name: string
    value: string
}

declare interface SystemECDSAKey {
    curve: string
}


