// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface TeamMember {
    team_id: string
    user_id: string
    roles: string
    delete_at: number
    scheme_user: boolean
    scheme_admin: boolean
    explicit_roles: string
}

declare interface TeamUnread {
    team_id: string
    msg_count: number
    mention_count: number
}


