// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface Team {
    id: string
    create_at: number
    update_at: number
    delete_at: number
    display_name: string
    name: string
    description: string
    email: string
    type: string
    company_name: string
    allowed_domains: string
    invite_id: string
    allow_open_invite: boolean
    last_team_icon_update: number
    scheme_id: string
}

declare interface TeamPatch {
    display_name: string
    description: string
    company_name: string
    allowed_domains: string
    invite_id: string
    allow_open_invite: boolean
}


