// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface TeamStats {
    team_id: string
    total_member_count: number
    active_member_count: number
}


