// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface TermsOfService {
    id: string
    create_at: number
    user_id: string
    text: string
}


