// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface UserAccessToken {
    id: string
    token: string
    user_id: string
    description: string
    is_active: boolean
}


