// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface UserSearch {
    term: string
    team_id: string
    not_in_team_id: string
    in_channel_id: string
    not_in_channel_id: string
    allow_inactive: boolean
    without_team: boolean
    limit: number
    role: string
}


