// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface User {
    id: string
    create_at: number
    update_at: number
    delete_at: number
    username: string
    password: string
    auth_data: string
    auth_service: string
    email: string
    email_verified: boolean
    nickname: string
    first_name: string
    last_name: string
    position: string
    roles: string
    allow_marketing: boolean
    props: Map<string, string>
    notify_props: Map<string, string>
    last_password_update: number
    last_picture_update: number
    failed_attempts: number
    locale: string
    timezone: Map<string, string>
    mfa_active: boolean
    mfa_secret: string
    last_activity_at: number
}

declare interface UserPatch {
    username: string
    nickname: string
    first_name: string
    last_name: string
    position: string
    email: string
    props: Map<string, string>
    notify_props: Map<string, string>
    locale: string
    timezone: Map<string, string>
}

declare interface UserAuth {
    password: string
    auth_data: string
    auth_service: string
}


