// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface UserTermsOfService {
    user_id: string
    terms_of_service_id: string
    create_at: number
}


