// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface AppError {
    id: string
    message: string
    detailed_error: string
    request_id: string
    status_code: number
    is_oauth: boolean
}


