// Type definition automatically generated by [mattermost-typegen](https://github.com/cometkim/mattermost-typegen)

declare interface WebsocketBroadcast {
    user_id: string
    channel_id: string
    team_id: string
}

declare interface WebSocketEvent {
    event: string
    seq: number
}

declare interface WebSocketResponse {
    status: string
    seq_reply: number
}


